### ISSUE TITLE
请问ticket怎么更新呢？

### ISSUE THREAD

**Issue by chapin666** [reezon/wxapp-open-api#1]
请问ticket怎么更新呢？是否可以传一个获 ticket 的函数。

**Comment by reezon** [comment]
@chapin666 

微信服务器 每隔10分钟会向您配置的第三方的消息接收地址，推送一次InfoType == 'component_verify_ticket'的消息，消息体中有ticket。

此时需要把ticket存到数据库里。

然后在每次初始化本API对象的时候，通过参数componentVerifyTicket将ticket传入本API对象。

**Comment by chapin666** [comment]
谢谢。
但我是在启动服务的时候仅仅初始化对象一次，这样ticket过期后请求就无效了。
我这种猜想对吗？

**Comment by reezon** [comment]
@chapin666 
明白了，因为API对象的初始化参数是照着某著名公众号第三方api项目来写的，所以当时没考虑这个情况。
稍后我commit一个版本，在初始化参数中加上getComponentVerifyTicket 方法

**Comment by reezon** [comment]
@chapin666 已经为构造函数增加传入参数getComponentVerifyTicket

**Comment by chapin666** [comment]
多谢
