### ISSUE TITLE
初始化和授权逻辑有冲突

### ISSUE THREAD

**Issue by Nxys** [reezon/wxapp-open-api#3]
初始化需要授权刷新token，但是这个刷新token需要api_query_auth接口获取，这里是有冲突的，还是说我没搞清应该在什么时候new API()？

**Comment by reezon** [comment]
> 初始化需要授权刷新token，但是这个刷新token需要api_query_auth接口获取，这里是有冲突的，还是说我没搞清应该在什么时候new API()？

在第一次new API()的时候，可以不传 authorizerAppid, authorizerRefreshToken
通过这个API对象就能调用createPreAuthCode 和 queryAuth 来生成授权链接给用户

当用户授权之后，拿到了用户的authorizerAppid, authorizerRefreshToken，存下来。下次用户调用接口的时候，再使用这些参数new API()

即：new API()并不是进程启动的时候全局new，而是在每个接口里针对不同的用户来new
