### ISSUE TITLE
什么时候更新类目管理相关的接口

### ISSUE THREAD

**Issue by jia-zhen** [reezon/wxapp-open-api#5]
大佬，能添加类目管理相关接口吗

**Comment by reezon** [comment]
> 大佬，能添加类目管理相关接口吗

如果您是指的是[小程序类目管理](https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/category/getallcategories.html)下的api接口的话，
在api_code.js中有getCategory
在api_account.js中有其它接口
如果缺少哪些，可以继续回复该issue

**Comment by jia-zhen** [comment]
好的，感谢
